# Generated by Django 6.0.2 on 2026-02-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=20)),
                ('max_participants', models.PositiveIntegerField()),
                ('price_member', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_non_member', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allow_half', models.BooleanField(default=False)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('locations', models.ManyToManyField(blank=True, to='courses.location')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bank_details', models.CharField(max_length=200)),
                ('is_member', models.BooleanField(default=False)),
                ('half_course', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLIST', 'Waitlist')], default='CONFIRMED', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
