# Generated by Django 6.0.2 on 2026-02-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
