# Generated by Django 6.0.2 on 2026-02-20 07:41

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_registration_bank_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Ort', 'verbose_name_plural': 'Orte'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Anmeldung', 'verbose_name_plural': 'Anmeldungen'},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='bank_details',
        ),
        migrations.AlterField(
            model_name='course',
            name='allow_half',
            field=models.BooleanField(default=False, verbose_name='Halber Kurs erlaubt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=20, verbose_name='Wochentage'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kursleitung'),
        ),
        migrations.AlterField(
            model_name='course',
            name='locations',
            field=models.ManyToManyField(blank=True, to='courses.location', verbose_name='Orte'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_participants',
            field=models.PositiveIntegerField(verbose_name='Maximale Teilnehmer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Kursname'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_member',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis Mitglied'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_non_member',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis Nicht-Mitglied'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='half_course',
            field=models.BooleanField(default=False, verbose_name='Halber Kurs'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Mitglied'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Bestätigt'), ('WAITLIST', 'Warteliste')], default='CONFIRMED', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Bedingungen akzeptiert'),
        ),
    ]
