# Generated by hand - run `python manage.py makemigrations` to regenerate
from django.conf import settings
from django.db import migrations, models


def copy_instructor(apps, schema_editor):
    """Try to migrate existing text instructors to the new FK.

    The algorithm is best-effort: if the text matches an existing user's full
    name or email we assign that user.  Otherwise the field is left blank and
    can be filled manually later via the admin.
    """
    Course = apps.get_model('courses', 'Course')
    # we can't reliably use apps.get_model for the user model because the
    # label varies when AUTH_USER_MODEL is swapped; instead import the
    # runtime model via get_user_model().
    from django.contrib.auth import get_user_model
    User = get_user_model()

    for course in Course.objects.all():
        name = course.instructor.strip() if course.instructor else ''
        if not name:
            continue
        # try matching by email first
        try:
            user = User.objects.get(email__iexact=name)
        except User.DoesNotExist:
            # try matching by full name
            parts = name.split()
            if len(parts) >= 2:
                first, last = parts[0], parts[-1]
                try:
                    user = User.objects.get(first_name__iexact=first, last_name__iexact=last)
                except User.DoesNotExist:
                    user = None
            else:
                user = None
        if user:
            course.instructor_user = user
            course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_location_options_course_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Kursleitung (Benutzer)',
                help_text='Wähle den Benutzer, der für diesen Kurs verantwortlich ist.',
            ),
        ),
        migrations.RunPython(copy_instructor, migrations.RunPython.noop),
    ]
