# Generated by ChatGPT - update weekday codes
from django.db import migrations


def forwards(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    mapping = {
        'MO': 'Mo',
        'TU': 'Di',
        'WE': 'Mi',
        'TH': 'Do',
        'FR': 'Fr',
        'SA': 'Sa',
        'SU': 'So',
    }
    for course in Course.objects.all():
        if course.days:
            new_days = []
            for d in course.days:
                new_days.append(mapping.get(d, d))
            course.days = new_days
            course.save()


def backwards(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    reverse = {
        'Mo': 'MO',
        'Di': 'TU',
        'Mi': 'WE',
        'Do': 'TH',
        'Fr': 'FR',
        'Sa': 'SA',
        'So': 'SU',
    }
    for course in Course.objects.all():
        if course.days:
            old_days = []
            for d in course.days:
                old_days.append(reverse.get(d, d))
            course.days = old_days
            course.save()


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0007_add_instructor_user'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
