# Generated by Django 6.0.2 on 2026-03-03 08:34

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_update_weekday_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurse'},
        ),
        migrations.AddField(
            model_name='course',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, können sich keine neuen Teilnehmer anmelden.', verbose_name='Anmeldung gesperrt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag'), ('Sa', 'Samstag'), ('So', 'Sonntag')], max_length=20, verbose_name='Wochentage'),
        ),
    ]
