# Generated by Django 6.0.2 on 2026-03-05 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_add_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Storno-Token'),
        ),
    ]
