# Generated by Django 6.0.2 on 2026-03-05 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_add_cancel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Storno-Token'),
        ),
    ]
