# Generated by Django 6.0.2 on 2026-03-06 07:39

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_cancel_token_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('WATER', 'Wasserkurs'), ('HALL', 'Hallenkurs'), ('OTHER', 'Sonstiges')], default='OTHER', max_length=10, verbose_name='Kurstyp'),
        ),
        migrations.AddField(
            model_name='course',
            name='num_sessions',
            field=models.PositiveIntegerField(blank=True, help_text='Nur fuer Modus "Einheitenanzahl". Enddatum wird automatisch berechnet.', null=True, verbose_name='Anzahl Einheiten'),
        ),
        migrations.AddField(
            model_name='course',
            name='publish_from',
            field=models.DateField(blank=True, help_text='Leer = sofort sichtbar. Sonst wird der Kurs erst ab diesem Datum angezeigt.', null=True, verbose_name='Sichtbar ab'),
        ),
        migrations.AddField(
            model_name='course',
            name='session_mode',
            field=models.CharField(choices=[('AUTO', 'Automatisch (Start + Ende + Wochentage, NRW-Feiertage uebersprungen)'), ('COUNT', 'Einheitenanzahl (Start + Wochentage + Anzahl, Enddatum wird berechnet)'), ('MANUAL', 'Manuell (Einzeltermine selbst bestimmen)')], default='AUTO', max_length=10, verbose_name='Einheitenmodus'),
        ),
        migrations.AddField(
            model_name='registration',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wenn gesetzt, wird dieser Betrag statt des Standardpreises verwendet (z.B. bei Verletzung).', max_digits=6, null=True, verbose_name='Individualbetrag'),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional, fuer Rueckfragen.', max_length=30, verbose_name='Handy / Telefon'),
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag'), ('Sa', 'Samstag'), ('So', 'Sonntag')], max_length=20, verbose_name='Wochentage'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_user',
            field=models.ForeignKey(blank=True, help_text='Waehle den Benutzer, der fuer diesen Kurs verantwortlich ist.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kursleitung (Benutzer)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, koennen sich keine neuen Teilnehmer anmelden.', verbose_name='Anmeldung gesperrt'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Bestaetigt'), ('WAITLIST', 'Warteliste'), ('CANCELLED', 'Storniert')], default='CONFIRMED', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Einheit faellt aus (z.B. nachtraeglicher Feiertag, Ausnahme).', verbose_name='Ausgefallen')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Hinweis')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
                'ordering': ['date'],
            },
        ),
    ]
