# Generated by Django 6.0.2 on 2026-03-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_phase1_sessions_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(help_text='Fuer Rueckfragen bei Kursaenderungen.', max_length=30, verbose_name='Handy / Telefon'),
        ),
    ]
