# Generated by Django 6.0.2 on 2026-03-25 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_phone_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_user',
            field=models.ForeignKey(blank=True, help_text='Wähle den Benutzer, der für diesen Kurs verantwortlich ist.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kursleitung (Benutzer)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, können sich keine neuen Teilnehmer anmelden.', verbose_name='Anmeldung gesperrt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_sessions',
            field=models.PositiveIntegerField(blank=True, help_text='Nur für Modus "Einheitenanzahl". Enddatum wird automatisch berechnet.', null=True, verbose_name='Anzahl Einheiten'),
        ),
        migrations.AlterField(
            model_name='course',
            name='session_mode',
            field=models.CharField(choices=[('AUTO', 'Automatisch (Start + Ende + Wochentage, NRW-Feiertage übersprungen)'), ('COUNT', 'Einheitenanzahl (Start + Wochentage + Anzahl, Enddatum wird berechnet)'), ('MANUAL', 'Manuell (Einzeltermine selbst bestimmen)')], default='AUTO', max_length=10, verbose_name='Einheitenmodus'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Einheit fällt aus (z.B. nachträglicher Feiertag, Ausnahme.', verbose_name='Ausgefallen'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(help_text='Für Rückfragen bei Kursänderungen.', max_length=30, verbose_name='Handy / Telefon'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Bestätigt'), ('WAITLIST', 'Warteliste'), ('CANCELLED', 'Storniert')], default='CONFIRMED', max_length=10, verbose_name='Status'),
        ),
    ]
