# Generated by Django 6.0.2 on 2026-04-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_instructor_user_alter_course_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='close_on_start',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, ist eine Anmeldung nach dem Startdatum des Kurses nicht mehr möglich.', verbose_name='Anmeldung bei Kursbeginn sperren'),
        ),
    ]
